### ISSUE TITLE
Could you provide all the codes? and How to cite your work? Thank you very much!

### ISSUE THREAD

**Issue by guyucowboy** [andy1445/deep_learning_reu#3]
Hi,andy.
Could you provide all the codes? How to cite your work? Which paper are related to the project?
Thank you for sharing very much!
Best regard.
Yu Gu

**Comment by chufangao** [comment]
Sorry for the late response, but unfortunately, I don't have some of the preprocessing files anymore. However, the main model should be pretty easy to interpret / reimplement on your application since it's just a 3d GAN essentially.

I've updated the README with our publication and the bibtex. Thank you for your interest!
